/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/forms/waitlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get waitlist projects. */
        get: {
            parameters: {
                query: {
                    limit: string;
                    offset: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetWaitlistProjectsResponse"];
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a waitlist project. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWaitlistProjectRequestBody"];
                };
            };
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateWaitlistProjectResponse"];
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/waitlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get basic information of a waitlist project. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetWaitlistProjectResponse"];
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        /** @description Update basic information of a waitlist project. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWaitlistProjectRequestBody"];
                };
            };
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteWaitlistProjectResponse"];
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        /** @description Create a waitlist item for a project. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWaitlistItemRequestBody"];
                };
            };
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateWaitlistItemtResponse"];
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundResponse"];
                    };
                };
                /** @description Conflict request. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConflictResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        /** @description Delete a waitlist project. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteWaitlistProjectResponse"];
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/waitlists/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get waitlist items of a project. */
        get: {
            parameters: {
                query: {
                    limit: string;
                    offset: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetWaitlistItemResponse"];
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/waitlists/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get information of a waitlist item. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetWaitlistItemResponse"] & {
                            /**
                             * @description Response message.
                             * @example This is a message.
                             */
                            message: string;
                            item: components["schemas"]["WaitlistItem"];
                        };
                    };
                };
                /** @description Unauthorized. Your root key do not have permissions. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnauthorizedResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundResponse"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WaitlistProject: {
            id: string;
            name: string;
            description: string | null;
            teamId: string;
            createdAt: string;
            /** @enum {string} */
            createdWay: "dashboard" | "openapi";
        };
        CreateWaitlistProjectResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
            project: components["schemas"]["WaitlistProject"];
        };
        UnauthorizedResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
        };
        InternalServerErrorResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
        };
        CreateWaitlistProjectRequestBody: {
            /**
             * @description Name
             * @example This is a name.
             */
            name: string;
            /**
             * @description Description
             * @example This is a description.
             */
            description: string;
        };
        WaitlistProjectDetail: {
            id: string;
            name: string;
            description: string | null;
            teamId: string;
            createdAt: string;
            /** @enum {string} */
            createdWay: "dashboard" | "openapi";
            /**
             * @description The amount of the resource.
             * @example 16
             */
            total: number;
        };
        WaitlistProjects: components["schemas"]["WaitlistProjectDetail"][];
        GetWaitlistProjectsResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
            projects: components["schemas"]["WaitlistProjects"];
            /**
             * @description The amount of the resource.
             * @example 16
             */
            total: number;
        };
        GetWaitlistProjectResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
            project: components["schemas"]["WaitlistProjectDetail"];
        };
        NotFoundResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
        };
        DeleteWaitlistProjectResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
        };
        UpdateWaitlistProjectRequestBody: {
            /**
             * @description Name
             * @example This is a name.
             */
            name?: string;
            /**
             * @description Description
             * @example This is a description.
             */
            description?: string;
        };
        WaitlistItem: {
            id: string;
            projectId: string;
            email: string;
            createdAt: string;
        };
        CreateWaitlistItemtResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
            item: components["schemas"]["WaitlistItem"];
        };
        ConflictResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
        };
        CreateWaitlistItemRequestBody: {
            /**
             * Format: email
             * @description Email address.
             * @example m@example.com
             */
            email: string;
        };
        GetWaitlistItemResponse: {
            /**
             * @description Response message.
             * @example This is a message.
             */
            message: string;
            items: components["schemas"]["WaitlistItem"] & {
                id: string;
                projectId: string;
                email: string;
                createdAt: string;
            }[];
            /**
             * @description The amount of the resource.
             * @example 16
             */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
